In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data_cats = ["NoTaxRatios","WithTaxRatios"]
dcts = {}
for data_cat in data_cats:
    filename = f"panelData{data_cat}.xlsx"
    dcts[data_cat] = pd.read_excel(filename,sheet_name=None)
dcts

{'NoTaxRatios': {'Levels':       Unnamed: 0 State       DATE  Population  Home Price Index  EFNA  \
  0              0    AL 1900-01-01     1830.00               NaN   NaN
  1              1    AL 1901-01-01     1907.00               NaN   NaN
  2              2    AL 1902-01-01     1935.00               NaN   NaN
  3              3    AL 1903-01-01     1957.00               NaN   NaN
  4              4    AL 1904-01-01     1978.00               NaN   NaN
  ...          ...   ...        ...         ...               ...   ...
  6195        6195    WY 2019-01-01      580.12            324.49  8.16
  6196        6196    WY 2020-01-01      577.66            340.92  8.01
  6197        6197    WY 2021-01-01      579.55            380.47  7.99
  6198        6198    WY 2022-01-01      581.63            438.83   NaN
  6199        6199    WY 2023-01-01      584.06            459.80   NaN

        Overall-scores(allgovs)   3A-allg   3B-allg   3C-allg  ...  \
  0                         NaN       NaN       NaN       NaN  ...
  1                         NaN       NaN       NaN       NaN  ...
  2                         NaN       NaN       NaN       NaN  ...
  3                         NaN       NaN       NaN       NaN  ...
  4                         NaN       NaN       NaN       NaN  ...
  ...                       ...       ...       ...       ...  ...
  6195                 8.156352  8.658398  8.987214  8.084057  ...
  6196                 8.009364  8.668255  7.312681  8.039567  ...
  6197                 7.988226  8.811210  7.410669  6.756226  ...
  6198                      NaN       NaN       NaN       NaN  ...
  6199                      NaN       NaN       NaN       NaN  ...

        Other License Taxes (T29)  Total Income Taxes  \
  0                           NaN                 NaN
  1                           NaN                 NaN
  2                           NaN                 NaN
  3                           NaN                 NaN
  4                           NaN                 NaN
  ...                         ...                 ...
  6195                        0.0                 0.0
  6196                        0.0                 0.0
  6197                        0.0                 0.0
  6198                        0.0                 0.0
  6199                        0.0                 0.0

        Individual Income Tax (T40)  Corp Net Income Tax (T41)  \
  0                             NaN                        NaN
  1                             NaN                        NaN
  2                             NaN                        NaN
  3                             NaN                        NaN
  4                             NaN                        NaN
  ...                           ...                        ...
  6195                          0.0                        0.0
  6196                          0.0                        0.0
  6197                          0.0                        0.0
  6198                          0.0                        0.0
  6199                          0.0                        0.0

        Total Other Taxes  Death and Gift Tax (T50)  \
  0                   NaN                       NaN
  1                   NaN                       NaN
  2                   NaN                       NaN
  3                   NaN                       NaN
  4                   NaN                       NaN
  ...                 ...                       ...
  6195           674540.0                       0.0
  6196           511347.0                       0.0
  6197           439365.0                       0.0
  6198           778220.0                       0.0
  6199          1155472.0                       0.0

        Docum and Stock Tr Tax (T51)  Severance Tax (T53)  Taxes NEC (T99)  \
  0                              NaN                  NaN              NaN
  1                              NaN                  NaN              NaN
  2                              NaN                  NaN              NaN
  3                              NaN                  NaN              NaN
  4                              NaN                  NaN              NaN
  ...                            ...                  ...              ...
  6195                           0.0             668178.0           6362.0
  6196                           0.0             505573.0           5774.0
  6197                           0.0             435314.0           4051.0
  6198                           0.0             770487.0           7733.0
  6199                           0.0            1145516.0           9956.0

        GDP Per Capita
  0                NaN
  1                NaN
  2                NaN
  3                NaN
  4                NaN
  ...              ...
  6195       69.675412
  6196       62.738462
  6197             NaN
  6198             NaN
  6199             NaN

  [6200 rows x 54 columns],
  'Log':       Unnamed: 0 State       DATE        GDP  Population  GDP Per Capita  \
  0              0    AL 1900-01-01        NaN    7.512071             NaN
  1              1    AL 1901-01-01        NaN    7.553287             NaN
  2              2    AL 1902-01-01        NaN    7.567863             NaN
  3              3    AL 1903-01-01        NaN    7.579168             NaN
  4              4    AL 1904-01-01        NaN    7.589842             NaN
  ...          ...   ...        ...        ...         ...             ...
  6195        6195    WY 2019-01-01  10.607082    6.363235        4.243847
  6196        6196    WY 2020-01-01  10.497960    6.358985        4.138975
  6197        6197    WY 2021-01-01        NaN    6.362252             NaN
  6198        6198    WY 2022-01-01        NaN    6.365835             NaN
  6199        6199    WY 2023-01-01        NaN    6.370004             NaN

        Home Price Index  Private GDP  Government Spending  \
  0                  NaN          NaN                  NaN
  1                  NaN          NaN                  NaN
  2                  NaN          NaN                  NaN
  3                  NaN          NaN                  NaN
  4                  NaN          NaN                  NaN
  ...                ...          ...                  ...
  6195          5.782255    10.429100             6.493905
  6196          5.831648    10.296789             6.397263
  6197          5.941407          NaN                  NaN
  6198          6.084112          NaN                  NaN
  6199          6.130792          NaN                  NaN

        State and Local Spending  Total Income Taxes  Total Taxes  \
  0                          NaN                 NaN          NaN
  1                          NaN                 NaN          NaN
  2                          NaN                 NaN          NaN
  3                          NaN                 NaN          NaN
  4                          NaN                 NaN          NaN
  ...                        ...                 ...          ...
  6195                  8.555009                 NaN    14.562532
  6196                  8.542939                 NaN    14.490441
  6197                       NaN                 NaN    14.444053
  6198                       NaN                 NaN    14.707921
  6199                       NaN                 NaN    15.023541

        Property Tax (T01)  EFNA  Average 3-6
  0                    NaN   NaN          NaN
  1                    NaN   NaN          NaN
  2                    NaN   NaN          NaN
  3                    NaN   NaN          NaN
  4                    NaN   NaN          NaN
  ...                  ...   ...          ...
  6195           12.519123  8.16     8.449764
  6196           12.598057  8.01     8.238549
  6197           12.597861  7.99     8.241616
  6198           12.499831   NaN          NaN
  6199           13.075171   NaN          NaN

  [6200 rows x 15 columns],
  'Rates':       Unnamed: 0 State       DATE  Population  Home Price Index  EFNA  \
  0              0    AL 1900-01-01         NaN               NaN   NaN
  1              1    AL 1901-01-01    0.041215               NaN   NaN
  2              2    AL 1902-01-01    0.014576               NaN   NaN
  3              3    AL 1903-01-01    0.011305               NaN   NaN
  4              4    AL 1904-01-01    0.010674               NaN   NaN
  ...          ...   ...        ...         ...               ...   ...
  6195        6195    WY 2019-01-01    0.001846          0.041176  8.16
  6196        6196    WY 2020-01-01   -0.004250          0.049393  8.01
  6197        6197    WY 2021-01-01    0.003266          0.109759  7.99
  6198        6198    WY 2022-01-01    0.003583          0.142705   NaN
  6199        6199    WY 2023-01-01    0.004169          0.046680   NaN

        Overall-scores(allgovs)   3A-allg   3B-allg   3C-allg  ...  \
  0                         NaN       NaN       NaN       NaN  ...
  1                         NaN       NaN       NaN       NaN  ...
  2                         NaN       NaN       NaN       NaN  ...
  3                         NaN       NaN       NaN       NaN  ...
  4                         NaN       NaN       NaN       NaN  ...
  ...                       ...       ...       ...       ...  ...
  6195                 8.156352  8.658398  8.987214  8.084057  ...
  6196                 8.009364  8.668255  7.312681  8.039567  ...
  6197                 7.988226  8.811210  7.410669  6.756226  ...
  6198                      NaN       NaN       NaN       NaN  ...
  6199                      NaN       NaN       NaN       NaN  ...

        Other License Taxes (T29)  Total Income Taxes  \
  0                           NaN                 NaN
  1                           NaN                 NaN
  2                           NaN                 NaN
  3                           NaN                 NaN
  4                           NaN                 NaN
  ...                         ...                 ...
  6195                        0.0                 NaN
  6196                        0.0                 NaN
  6197                        0.0                 NaN
  6198                        0.0                 NaN
  6199                        0.0                 NaN

        Individual Income Tax (T40)  Corp Net Income Tax (T41)  \
  0                             NaN                        NaN
  1                             NaN                        NaN
  2                             NaN                        NaN
  3                             NaN                        NaN
  4                             NaN                        NaN
  ...                           ...                        ...
  6195                          0.0                        0.0
  6196                          0.0                        0.0
  6197                          0.0                        0.0
  6198                          0.0                        0.0
  6199                          0.0                        0.0

        Total Other Taxes  Death and Gift Tax (T50)  \
  0                   NaN                       NaN
  1                   NaN                       NaN
  2                   NaN                       NaN
  3                   NaN                       NaN
  4                   NaN                       NaN
  ...                 ...                       ...
  6195           0.319581                       0.0
  6196           0.260374                       0.0
  6197           0.234343                       0.0
  6198           0.318811                       0.0
  6199           0.345238                       0.0

        Docum and Stock Tr Tax (T51)  Severance Tax (T53)  Taxes NEC (T99)  \
  0                              NaN                  NaN              NaN
  1                              NaN                  NaN              NaN
  2                              NaN                  NaN              NaN
  3                              NaN                  NaN              NaN
  4                              NaN                  NaN              NaN
  ...                            ...                  ...              ...
  6195                           0.0             0.316566         0.003014
  6196                           0.0             0.257434         0.002940
  6197                           0.0             0.232183         0.002161
  6198                           0.0             0.315643         0.003168
  6199                           0.0             0.342263         0.002975

        GDP Per Capita
  0                NaN
  1                NaN
  2                NaN
  3                NaN
  4                NaN
  ...              ...
  6195        0.016049
  6196       -0.104873
  6197             NaN
  6198             NaN
  6199             NaN

  [6200 rows x 54 columns],
  '5YearRates':       Unnamed: 0 State       DATE  Population  Home Price Index  EFNA  \
  0              0    AL 1900-01-01         NaN               NaN   NaN
  1              1    AL 1901-01-01         NaN               NaN   NaN
  2              2    AL 1902-01-01         NaN               NaN   NaN
  3              3    AL 1903-01-01         NaN               NaN   NaN
  4              4    AL 1904-01-01         NaN               NaN   NaN
  ...          ...   ...        ...         ...               ...   ...
  6195        6195    WY 2019-01-01   -0.005227          0.144612  8.16
  6196        6196    WY 2020-01-01   -0.015000          0.159081  8.01
  6197        6197    WY 2021-01-01   -0.009770          0.248753  7.99
  6198        6198    WY 2022-01-01    0.002824          0.377633   NaN
  6199        6199    WY 2023-01-01    0.008615          0.389713   NaN

        Overall-scores(allgovs)   3A-allg   3B-allg   3C-allg  ...  \
  0                         NaN       NaN       NaN       NaN  ...
  1                         NaN       NaN       NaN       NaN  ...
  2                         NaN       NaN       NaN       NaN  ...
  3                         NaN       NaN       NaN       NaN  ...
  4                         NaN       NaN       NaN       NaN  ...
  ...                       ...       ...       ...       ...  ...
  6195                 8.156352  8.658398  8.987214  8.084057  ...
  6196                 8.009364  8.668255  7.312681  8.039567  ...
  6197                 7.988226  8.811210  7.410669  6.756226  ...
  6198                      NaN       NaN       NaN       NaN  ...
  6199                      NaN       NaN       NaN       NaN  ...

        Other License Taxes (T29)  Total Income Taxes  \
  0                           NaN                 NaN
  1                           NaN                 NaN
  2                           NaN                 NaN
  3                           NaN                 NaN
  4                           NaN                 NaN
  ...                         ...                 ...
  6195                        0.0                 NaN
  6196                        0.0                 NaN
  6197                        0.0                 NaN
  6198                        0.0                 NaN
  6199                        0.0                 NaN

        Individual Income Tax (T40)  Corp Net Income Tax (T41)  \
  0                             NaN                        NaN
  1                             NaN                        NaN
  2                             NaN                        NaN
  3                             NaN                        NaN
  4                             NaN                        NaN
  ...                           ...                        ...
  6195                          0.0                        0.0
  6196                          0.0                        0.0
  6197                          0.0                        0.0
  6198                          0.0                        0.0
  6199                          0.0                        0.0

        Total Other Taxes  Death and Gift Tax (T50)  \
  0                   NaN                       NaN
  1                   NaN                       NaN
  2                   NaN                       NaN
  3                   NaN                       NaN
  4                   NaN                       NaN
  ...                 ...                       ...
  6195           0.319581                       0.0
  6196           0.260374                       0.0
  6197           0.234343                       0.0
  6198           0.318811                       0.0
  6199           0.345238                       0.0

        Docum and Stock Tr Tax (T51)  Severance Tax (T53)  Taxes NEC (T99)  \
  0                              NaN                  NaN              NaN
  1                              NaN                  NaN              NaN
  2                              NaN                  NaN              NaN
  3                              NaN                  NaN              NaN
  4                              NaN                  NaN              NaN
  ...                            ...                  ...              ...
  6195                           0.0             0.316566         0.003014
  6196                           0.0             0.257434         0.002940
  6197                           0.0             0.232183         0.002161
  6198                           0.0             0.315643         0.003168
  6199                           0.0             0.342263         0.002975

        GDP Per Capita
  0                NaN
  1                NaN
  2                NaN
  3                NaN
  4                NaN
  ...              ...
  6195        0.029984
  6196       -0.028709
  6197             NaN
  6198             NaN
  6199             NaN

  [6200 rows x 54 columns],
  'DiffRates':      Unnamed: 0 State       DATE       GDP  Population  GDP Per Capita  \
  0             0    AL 2001-01-01 -0.012576   -0.015194        0.002619
  1             1    AL 2002-01-01  0.016603   -0.000681        0.017284
  2             2    AL 2003-01-01  0.004188    0.002424        0.001763
  3             3    AL 2004-01-01  0.047387    0.000821        0.046566
  4             4    AL 2005-01-01 -0.029274    0.002556       -0.031830
  ..          ...   ...        ...       ...         ...             ...
  915         915    WI 2016-01-01 -0.019796    0.000432       -0.020227
  916         916    WI 2017-01-01  0.000222    0.000987       -0.000764
  917         917    WI 2018-01-01  0.028881   -0.000321        0.029202
  918         918    WI 2019-01-01 -0.016956   -0.000164       -0.016792
  919         919    WI 2020-01-01 -0.065755    0.009683       -0.075438

       Home Price Index  Private GDP  Government Spending  \
  0            0.029106    -0.013503            -0.098084
  1           -0.024853     0.010909             0.110752
  2            0.010126     0.006877            -0.041710
  3           -0.001546     0.058483             0.072942
  4            0.030708    -0.036033            -0.018861
  ..                ...          ...                  ...
  915          0.005931    -0.022920            -0.012774
  916          0.009723     0.000474             0.019466
  917          0.004168     0.029292             0.013423
  918         -0.006050    -0.019122             0.001552
  919         -0.002869    -0.066806            -0.138124

       State and Local Spending  Total Income Taxes  Total Taxes  EFNA  \
  0                    0.000420            0.053082    -0.018252 -0.14
  1                   -0.021956           -0.245892    -0.082816  0.01
  2                    0.016553            0.082078     0.021446  0.02
  3                   -0.007107            0.139706     0.104117  0.06
  4                    0.006834            0.038733     0.012628 -0.12
  ..                        ...                 ...          ...   ...
  915                  0.007394            0.003657    -0.002856  0.01

In [2]:
# example
dcts["WithTaxRatios"]

{'Levels':       Unnamed: 0 State       DATE  Population  Home Price Index  EFNA  \
 0              0    AL 1900-01-01     1830.00               NaN   NaN
 1              1    AL 1901-01-01     1907.00               NaN   NaN
 2              2    AL 1902-01-01     1935.00               NaN   NaN
 3              3    AL 1903-01-01     1957.00               NaN   NaN
 4              4    AL 1904-01-01     1978.00               NaN   NaN
 ...          ...   ...        ...         ...               ...   ...
 6195        6195    WY 2019-01-01      580.12            324.49  8.16
 6196        6196    WY 2020-01-01      577.66            340.92  8.01
 6197        6197    WY 2021-01-01      579.55            380.47  7.99
 6198        6198    WY 2022-01-01      581.63            438.83   NaN
 6199        6199    WY 2023-01-01      584.06            459.80   NaN

       Overall-scores(allgovs)   3A-allg   3B-allg   3C-allg  ...  \
 0                         NaN       NaN       NaN       NaN  ...
 1                         NaN       NaN       NaN       NaN  ...
 2                         NaN       NaN       NaN       NaN  ...
 3                         NaN       NaN       NaN       NaN  ...
 4                         NaN       NaN       NaN       NaN  ...
 ...                       ...       ...       ...       ...  ...
 6195                 8.156352  8.658398  8.987214  8.084057  ...
 6196                 8.009364  8.668255  7.312681  8.039567  ...
 6197                 7.988226  8.811210  7.410669  6.756226  ...
 6198                      NaN       NaN       NaN       NaN  ...
 6199                      NaN       NaN       NaN       NaN  ...

       Other License Taxes (T29)  Total Income Taxes  \
 0                           NaN                 NaN
 1                           NaN                 NaN
 2                           NaN                 NaN
 3                           NaN                 NaN
 4                           NaN                 NaN
 ...                         ...                 ...
 6195                        0.0                 0.0
 6196                        0.0                 0.0
 6197                        0.0                 0.0
 6198                        0.0                 0.0
 6199                        0.0                 0.0

       Individual Income Tax (T40)  Corp Net Income Tax (T41)  \
 0                             NaN                        NaN
 1                             NaN                        NaN
 2                             NaN                        NaN
 3                             NaN                        NaN
 4                             NaN                        NaN
 ...                           ...                        ...
 6195                          0.0                        0.0
 6196                          0.0                        0.0
 6197                          0.0                        0.0
 6198                          0.0                        0.0
 6199                          0.0                        0.0

       Total Other Taxes  Death and Gift Tax (T50)  \
 0                   NaN                       NaN
 1                   NaN                       NaN
 2                   NaN                       NaN
 3                   NaN                       NaN
 4                   NaN                       NaN
 ...                 ...                       ...
 6195           674540.0                       0.0
 6196           511347.0                       0.0
 6197           439365.0                       0.0
 6198           778220.0                       0.0
 6199          1155472.0                       0.0

       Docum and Stock Tr Tax (T51)  Severance Tax (T53)  Taxes NEC (T99)  \
 0                              NaN                  NaN              NaN
 1                              NaN                  NaN              NaN
 2                              NaN                  NaN              NaN
 3                              NaN                  NaN              NaN
 4                              NaN                  NaN              NaN
 ...                            ...                  ...              ...
 6195                           0.0             668178.0           6362.0
 6196                           0.0             505573.0           5774.0
 6197                           0.0             435314.0           4051.0
 6198                           0.0             770487.0           7733.0
 6199                           0.0            1145516.0           9956.0

       GDP Per Capita
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 6195       69.675412
 6196       62.738462
 6197             NaN
 6198             NaN
 6199             NaN

 [6200 rows x 54 columns],
 'Log':       Unnamed: 0 State       DATE        GDP  Population  GDP Per Capita  \
 0              0    AL 1900-01-01        NaN    7.512071             NaN
 1              1    AL 1901-01-01        NaN    7.553287             NaN
 2              2    AL 1902-01-01        NaN    7.567863             NaN
 3              3    AL 1903-01-01        NaN    7.579168             NaN
 4              4    AL 1904-01-01        NaN    7.589842             NaN
 ...          ...   ...        ...        ...         ...             ...
 6195        6195    WY 2019-01-01  10.607082    6.363235        4.243847
 6196        6196    WY 2020-01-01  10.497960    6.358985        4.138975
 6197        6197    WY 2021-01-01        NaN    6.362252             NaN
 6198        6198    WY 2022-01-01        NaN    6.365835             NaN
 6199        6199    WY 2023-01-01        NaN    6.370004             NaN

       Home Price Index  Private GDP  Government Spending  \
 0                  NaN          NaN                  NaN
 1                  NaN          NaN                  NaN
 2                  NaN          NaN                  NaN
 3                  NaN          NaN                  NaN
 4                  NaN          NaN                  NaN
 ...                ...          ...                  ...
 6195          5.782255    10.429100             6.493905
 6196          5.831648    10.296789             6.397263
 6197          5.941407          NaN                  NaN
 6198          6.084112          NaN                  NaN
 6199          6.130792          NaN                  NaN

       State and Local Spending  Total Income Taxes  Total Taxes  \
 0                          NaN                 NaN          NaN
 1                          NaN                 NaN          NaN
 2                          NaN                 NaN          NaN
 3                          NaN                 NaN          NaN
 4                          NaN                 NaN          NaN
 ...                        ...                 ...          ...
 6195                  8.555009                 NaN    14.562532
 6196                  8.542939                 NaN    14.490441
 6197                       NaN                 NaN    14.444053
 6198                       NaN                 NaN    14.707921
 6199                       NaN                 NaN    15.023541

       Property Tax (T01)  EFNA  Average 3-6
 0                    NaN   NaN          NaN
 1                    NaN   NaN          NaN
 2                    NaN   NaN          NaN
 3                    NaN   NaN          NaN
 4                    NaN   NaN          NaN
 ...                  ...   ...          ...
 6195           12.519123  8.16     8.449764
 6196           12.598057  8.01     8.238549
 6197           12.597861  7.99     8.241616
 6198           12.499831   NaN          NaN
 6199           13.075171   NaN          NaN

 [6200 rows x 15 columns],
 'Rates':       Unnamed: 0 State       DATE  Population  Home Price Index  EFNA  \
 0              0    AL 1900-01-01         NaN               NaN   NaN
 1              1    AL 1901-01-01    0.041215               NaN   NaN
 2              2    AL 1902-01-01    0.014576               NaN   NaN
 3              3    AL 1903-01-01    0.011305               NaN   NaN
 4              4    AL 1904-01-01    0.010674               NaN   NaN
 ...          ...   ...        ...         ...               ...   ...
 6195        6195    WY 2019-01-01    0.001846          0.041176  8.16
 6196        6196    WY 2020-01-01   -0.004250          0.049393  8.01
 6197        6197    WY 2021-01-01    0.003266          0.109759  7.99
 6198        6198    WY 2022-01-01    0.003583          0.142705   NaN
 6199        6199    WY 2023-01-01    0.004169          0.046680   NaN

       Overall-scores(allgovs)   3A-allg   3B-allg   3C-allg  ...  \
 0                         NaN       NaN       NaN       NaN  ...
 1                         NaN       NaN       NaN       NaN  ...
 2                         NaN       NaN       NaN       NaN  ...
 3                         NaN       NaN       NaN       NaN  ...
 4                         NaN       NaN       NaN       NaN  ...
 ...                       ...       ...       ...       ...  ...
 6195                 8.156352  8.658398  8.987214  8.084057  ...
 6196                 8.009364  8.668255  7.312681  8.039567  ...
 6197                 7.988226  8.811210  7.410669  6.756226  ...
 6198                      NaN       NaN       NaN       NaN  ...
 6199                      NaN       NaN       NaN       NaN  ...

       Other License Taxes (T29)  Total Income Taxes  \
 0                           NaN                 NaN
 1                           NaN                 NaN
 2                           NaN                 NaN
 3                           NaN                 NaN
 4                           NaN                 NaN
 ...                         ...                 ...
 6195                        0.0                 NaN
 6196                        0.0                 NaN
 6197                        0.0                 NaN
 6198                        0.0                 NaN
 6199                        0.0                 NaN

       Individual Income Tax (T40)  Corp Net Income Tax (T41)  \
 0                             NaN                        NaN
 1                             NaN                        NaN
 2                             NaN                        NaN
 3                             NaN                        NaN
 4                             NaN                        NaN
 ...                           ...                        ...
 6195                          0.0                        0.0
 6196                          0.0                        0.0
 6197                          0.0                        0.0
 6198                          0.0                        0.0
 6199                          0.0                        0.0

       Total Other Taxes  Death and Gift Tax (T50)  \
 0                   NaN                       NaN
 1                   NaN                       NaN
 2                   NaN                       NaN
 3                   NaN                       NaN
 4                   NaN                       NaN
 ...                 ...                       ...
 6195           0.319581                       0.0
 6196           0.260374                       0.0
 6197           0.234343                       0.0
 6198           0.318811                       0.0
 6199           0.345238                       0.0

       Docum and Stock Tr Tax (T51)  Severance Tax (T53)  Taxes NEC (T99)  \
 0                              NaN                  NaN              NaN
 1                              NaN                  NaN              NaN
 2                              NaN                  NaN              NaN
 3                              NaN                  NaN              NaN
 4                              NaN                  NaN              NaN
 ...                            ...                  ...              ...
 6195                           0.0             0.316566         0.003014
 6196                           0.0             0.257434         0.002940
 6197                           0.0             0.232183         0.002161
 6198                           0.0             0.315643         0.003168
 6199                           0.0             0.342263         0.002975

       GDP Per Capita
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 6195        0.016049
 6196       -0.104873
 6197             NaN
 6198             NaN
 6199             NaN

 [6200 rows x 54 columns],
 '5YearRates':       Unnamed: 0 State       DATE  Population  Home Price Index  EFNA  \
 0              0    AL 1900-01-01         NaN               NaN   NaN
 1              1    AL 1901-01-01         NaN               NaN   NaN
 2              2    AL 1902-01-01         NaN               NaN   NaN
 3              3    AL 1903-01-01         NaN               NaN   NaN
 4              4    AL 1904-01-01         NaN               NaN   NaN
 ...          ...   ...        ...         ...               ...   ...
 6195        6195    WY 2019-01-01   -0.005227          0.144612  8.16
 6196        6196    WY 2020-01-01   -0.015000          0.159081  8.01
 6197        6197    WY 2021-01-01   -0.009770          0.248753  7.99
 6198        6198    WY 2022-01-01    0.002824          0.377633   NaN
 6199        6199    WY 2023-01-01    0.008615          0.389713   NaN

       Overall-scores(allgovs)   3A-allg   3B-allg   3C-allg  ...  \
 0                         NaN       NaN       NaN       NaN  ...
 1                         NaN       NaN       NaN       NaN  ...
 2                         NaN       NaN       NaN       NaN  ...
 3                         NaN       NaN       NaN       NaN  ...
 4                         NaN       NaN       NaN       NaN  ...
 ...                       ...       ...       ...       ...  ...
 6195                 8.156352  8.658398  8.987214  8.084057  ...
 6196                 8.009364  8.668255  7.312681  8.039567  ...
 6197                 7.988226  8.811210  7.410669  6.756226  ...
 6198                      NaN       NaN       NaN       NaN  ...
 6199                      NaN       NaN       NaN       NaN  ...

       Other License Taxes (T29)  Total Income Taxes  \
 0                           NaN                 NaN
 1                           NaN                 NaN
 2                           NaN                 NaN
 3                           NaN                 NaN
 4                           NaN                 NaN
 ...                         ...                 ...
 6195                        0.0                 NaN
 6196                        0.0                 NaN
 6197                        0.0                 NaN
 6198                        0.0                 NaN
 6199                        0.0                 NaN

       Individual Income Tax (T40)  Corp Net Income Tax (T41)  \
 0                             NaN                        NaN
 1                             NaN                        NaN
 2                             NaN                        NaN
 3                             NaN                        NaN
 4                             NaN                        NaN
 ...                           ...                        ...
 6195                          0.0                        0.0
 6196                          0.0                        0.0
 6197                          0.0                        0.0
 6198                          0.0                        0.0
 6199                          0.0                        0.0

       Total Other Taxes  Death and Gift Tax (T50)  \
 0                   NaN                       NaN
 1                   NaN                       NaN
 2                   NaN                       NaN
 3                   NaN                       NaN
 4                   NaN                       NaN
 ...                 ...                       ...
 6195           0.319581                       0.0
 6196           0.260374                       0.0
 6197           0.234343                       0.0
 6198           0.318811                       0.0
 6199           0.345238                       0.0

       Docum and Stock Tr Tax (T51)  Severance Tax (T53)  Taxes NEC (T99)  \
 0                              NaN                  NaN              NaN
 1                              NaN                  NaN              NaN
 2                              NaN                  NaN              NaN
 3                              NaN                  NaN              NaN
 4                              NaN                  NaN              NaN
 ...                            ...                  ...              ...
 6195                           0.0             0.316566         0.003014
 6196                           0.0             0.257434         0.002940
 6197                           0.0             0.232183         0.002161
 6198                           0.0             0.315643         0.003168
 6199                           0.0             0.342263         0.002975

       GDP Per Capita
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 6195        0.029984
 6196       -0.028709
 6197             NaN
 6198             NaN
 6199             NaN

 [6200 rows x 54 columns],
 'DiffRates':      Unnamed: 0 State       DATE       GDP  Population  GDP Per Capita  \
 0             0    AL 2001-01-01 -0.012576   -0.015194        0.002619
 1             1    AL 2002-01-01  0.016603   -0.000681        0.017284
 2             2    AL 2003-01-01  0.004188    0.002424        0.001763
 3             3    AL 2004-01-01  0.047387    0.000821        0.046566
 4             4    AL 2005-01-01 -0.029274    0.002556       -0.031830
 ..          ...   ...        ...       ...         ...             ...
 915         915    WI 2016-01-01 -0.019796    0.000432       -0.020227
 916         916    WI 2017-01-01  0.000222    0.000987       -0.000764
 917         917    WI 2018-01-01  0.028881   -0.000321        0.029202
 918         918    WI 2019-01-01 -0.016956   -0.000164       -0.016792
 919         919    WI 2020-01-01 -0.065755    0.009683       -0.075438

      Home Price Index  Private GDP  Government Spending  \
 0            0.029106    -0.013503            -0.098084
 1           -0.024853     0.010909             0.110752
 2            0.010126     0.006877            -0.041710
 3           -0.001546     0.058483             0.072942
 4            0.030708    -0.036033            -0.018861
 ..                ...          ...                  ...
 915          0.005931    -0.022920            -0.012774
 916          0.009723     0.000474             0.019466
 917          0.004168     0.029292             0.013423
 918         -0.006050    -0.019122             0.001552
 919         -0.002869    -0.066806            -0.138124

      State and Local Spending  Total Income Taxes  Total Taxes  EFNA  \
 0                    0.000420            0.053082    -0.018252 -0.14
 1                   -0.021956           -0.245892    -0.082816  0.01
 2                    0.016553            0.082078     0.021446  0.02
 3                   -0.007107            0.139706     0.104117  0.06
 4                    0.006834            0.038733     0.012628 -0.12
 ..                        ...                 ...          ...   ...
 915                  0.007394            0.003657    -0.002856  0.01
 916                 -0.003462           -0.012499    -0.009041  0.05
 917                  0.026379            0.012876     0.004099 -0.02
 918                  0.004117            0.049201     0.028406 -0.05
 919                 -0.068584           -0.092912    -0.044879 -0.12

      Average 3-6  Property Tax (T01)
 0      -0.130578           -0.000786

In [3]:
dcts["WithTaxRatios"]["Log"]

,Unnamed: 0,State,DATE,GDP,Population,GDP Per Capita,Home Price Index,Private GDP,Government Spending,State and Local Spending,Total Income Taxes,Total Taxes,Property Tax (T01),EFNA,Average 3-6
0,0,AL,1900-01-01,NaN,7.512071,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,AL,1901-01-01,NaN,7.553287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,AL,1902-01-01,NaN,7.567863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,AL,1903-01-01,NaN,7.579168,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,AL,1904-01-01,NaN,7.589842,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6195,6195,WY,2019-01-01,10.607082,6.363235,4.243847,5.782255,10.429100,6.493905,8.555009,NaN,14.562532,12.519123,8.16,8.449764
6196,6196,WY,2020-01-01,10.497960,6.358985,4.138975,5.831648,10.296789,6.397263,8.542939,NaN,14.490441,12.598057,8.01,8.238549
6197,6197,WY,2021-01-01,NaN,6.362252,NaN,5.941407,NaN,NaN,NaN,NaN,14.444053,12.597861,7.99,8.241616
6198,6198,WY,2022-01-01,NaN,6.365835,NaN,6.084112,NaN,NaN,NaN,NaN,14.707921,12.499831,NaN,NaN
6199,6199,WY,2023-01-01,NaN,6.370004,NaN,6.130792,NaN,NaN,NaN,NaN,15.023541,13.075171,NaN,NaN

In [5]:
# remeber to set indices
dcts["WithTaxRatios"]["Log"].set_index(["State", "DATE"])

                  Unnamed: 0        GDP  Population  GDP Per Capita  \
State DATE
AL    1900-01-01           0        NaN    7.512071             NaN
      1901-01-01           1        NaN    7.553287             NaN
      1902-01-01           2        NaN    7.567863             NaN
      1903-01-01           3        NaN    7.579168             NaN
      1904-01-01           4        NaN    7.589842             NaN
...                      ...        ...         ...             ...
WY    2019-01-01        6195  10.607082    6.363235        4.243847
      2020-01-01        6196  10.497960    6.358985        4.138975
      2021-01-01        6197        NaN    6.362252             NaN
      2022-01-01        6198        NaN    6.365835             NaN
      2023-01-01        6199        NaN    6.370004             NaN

                  Home Price Index  Private GDP  Government Spending  \
State DATE
AL    1900-01-01               NaN          NaN                  NaN
      1901-01-01               NaN          NaN                  NaN
      1902-01-01               NaN          NaN                  NaN
      1903-01-01               NaN          NaN                  NaN
      1904-01-01               NaN          NaN                  NaN
...                            ...          ...                  ...
WY    2019-01-01          5.782255    10.429100             6.493905
      2020-01-01          5.831648    10.296789             6.397263
      2021-01-01          5.941407          NaN                  NaN
      2022-01-01          6.084112          NaN                  NaN
      2023-01-01          6.130792          NaN                  NaN

                  State and Local Spending  Total Income Taxes  Total Taxes  \
State DATE
AL    1900-01-01                       NaN                 NaN          NaN
      1901-01-01                       NaN                 NaN          NaN
      1902-01-01                       NaN                 NaN          NaN
      1903-01-01                       NaN                 NaN          NaN
      1904-01-01                       NaN                 NaN          NaN
...                                    ...                 ...          ...
WY    2019-01-01                  8.555009                 NaN    14.562532
      2020-01-01                  8.542939                 NaN    14.490441
      2021-01-01                       NaN                 NaN    14.444053
      2022-01-01                       NaN                 NaN    14.707921
      2023-01-01                       NaN                 NaN    15.023541

                  Property Tax (T01)  EFNA  Average 3-6
State DATE
AL    1900-01-01                 NaN   NaN          NaN
      1901-01-01                 NaN   NaN          NaN
      1902-01-01                 NaN   NaN          NaN
      1903-01-01                 NaN   NaN          NaN
      1904-01-01                 NaN   NaN          NaN
...                              ...   ...          ...
WY    2019-01-01           12.519123  8.16     8.449764
      2020-01-01           12.598057  8.01     8.238549
      2021-01-01           12.597861  7.99     8.241616
      2022-01-01           12.499831   NaN          NaN
      2023-01-01           13.075171   NaN          NaN

[6200 rows x 13 columns]