In [1]:
#plots.py
import os
import pandas
import pandas_datareader.data as web
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.transforms as mtransforms
import datetime
import math

def gather_data(data_codes, start, end = datetime.datetime.today(), freq = "A"):
    i = 0
    # dct.items() calls key and value that key points to
    for key, val in data_codes.items():
        if i == 0:
            # Create dataframe for first variable, then rename column
            df = web.DataReader(val, "fred", start, end).resample(freq).mean()
            df.rename(columns = {val:key}, inplace = True) 
            # setting i to None will cause the next block of code to execute,
            # placing data within df instead of creating a new dataframe for
            # each variable
            i = None
        else:
            # If dataframe already exists, add new column
            df[key] = web.DataReader(val, "fred", start, end).resample(freq).mean()

    return df

In [2]:
data_codes  = {#"IOER (%)":"IOER",
              "30 Y (%)": "DGS30",
              "EFFR (%)": "DFF",
              "1 M (%)": "DGS1MO",
              "3 M (%)": "DGS3MO",
              "6 M (%)": "DGS6MO",               
              "1 Y (%)": "DGS1",
              "2 Y (%)": "DGS2",
              "3 Y (%)": "DGS3",
              "5 Y (%)": "DGS5",
              "7 Y (%)": "DGS7",
              "10 Y (%)": "DGS10",
              "20 Y (%)": "DGS20",
              "RGDP":"GDPC1",
              "NGDP":"GDP",
              "5 Year TIPS":"DFII5",
              "10 Year TIPS": "DFII10",
             
}
               
# Select start and end dates
start = datetime.datetime(1983, 1, 1)
end = datetime.datetime.today()

# freq refers to data frequency. Choose "D", "W", "M", "Q", "A"
# a number may also be place in front of a letter. "2D" indicates
#       alternating days
data = gather_data(data_codes = data_codes, start = start, end = end, freq = "M")#.dropna()

In [3]:
# Interpolate Quarterly Data for Monthly comparisons
data["RGDP"] = data["RGDP"].interpolate(method='polynomial', order=3)
data["NGDP"] = data["NGDP"].interpolate(method='polynomial', order=3)

In [4]:
# Create Indicator Variables For Identifying Yield Curve Inversion and Recession
data["EFFR > 2Y"] = False
data["Recession"] = False
data["EFFR > 2Y"][data["2 Y (%)"] < data["EFFR (%)"]] = True
# Defnitions of Recession are somewhat controversial
#  Here I use a reasonable reformulation of the 2 consecutive quarters of real gdp contraction 
# If GDP is lower than it was 6 months ago (i.e., 2 quarters ago), indicate a recession
data["Recession"][data["RGDP"]<data["RGDP"].shift(6)] = True
data[data["Recession"]]

C:\Users\JLCat\AppData\Local\Temp\ipykernel_1468\491588744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["EFFR > 2Y"][data["2 Y (%)"] < data["EFFR (%)"]] = True
C:\Users\JLCat\AppData\Local\Temp\ipykernel_1468\491588744.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Recession"][data["RGDP"]<data["RGDP"].shift(6)] = True

,30 Y (%),EFFR (%),1 M (%),3 M (%),6 M (%),1 Y (%),2 Y (%),3 Y (%),5 Y (%),7 Y (%),10 Y (%),20 Y (%),RGDP,NGDP,5 Year TIPS,10 Year TIPS,EFFR > 2Y,Recession
DATE,,,,,,,,,,,,,,,,,,
1990-09-30,9.028947,8.195000,NaN,7.597895,7.698421,7.763158,8.079474,8.267368,8.513684,8.786842,8.893158,NaN,9352.215816,6009.761981,NaN,NaN,True,True
1990-10-31,8.857727,8.112581,NaN,7.400000,7.529545,7.551364,7.877727,8.068636,8.327727,8.593636,8.719545,NaN,9318.876000,6004.733000,NaN,NaN,True,True
1990-11-30,8.540500,7.806667,NaN,7.290500,7.385000,7.313500,7.599500,7.737000,8.022500,8.276500,8.392000,NaN,9292.169392,6006.161585,NaN,NaN,True,True
1990-12-31,8.237000,7.312903,NaN,6.949500,7.026500,7.050500,7.314000,7.466000,7.726500,8.000500,8.075000,NaN,9275.661751,6015.996772,NaN,NaN,False,True
1991-01-31,8.269524,6.906452,NaN,6.410476,6.575714,6.644286,7.125238,7.377619,7.700000,7.970476,8.091905,NaN,9275.276000,6035.178000,NaN,NaN,False,True
1991-02-28,8.034211,6.252500,NaN,6.116316,6.194737,6.266842,6.866842,7.077368,7.472632,7.732632,7.854737,NaN,9290.982788,6060.532444,NaN,NaN,False,True
1991-03-31,8.288000,6.115161,NaN,6.093500,6.198500,6.396000,7.103000,7.353500,7.772000,8.002500,8.110000,NaN,9319.113159,6093.872506,NaN,NaN,False,True
2001-09-30,5.482941,3.069000,2.675882,2.692353,2.705882,2.824706,3.118824,3.450588,4.115294,4.512353,4.731765,5.526471,13257.826529,10627.707306,NaN,NaN,False,True
2001-10-31,5.315455,2.485161,2.267273,2.197727,2.170909,2.330455,2.725909,3.136818,3.910000,4.307273,4.566818,5.339545,13284.881000,10660.465000,NaN,NaN,False,True
2008-08-31,4.501905,1.996452,1.678571,1.752857,1.967143,2.177143,2.420476,2.699048,3.141905,3.459048,3.885714,4.533810,15603.453374,14819.199388,1.148095,1.676190,False,True
2008-09-30,4.269048,1.811667,0.885714,1.146667,1.640952,1.912857,2.076190,2.315714,2.884286,3.248571,3.686190,4.323810,15482.980307,14714.811331,1.553333,1.850000,False,True
2008-10-31,4.173182,0.969355,0.291818,0.685909,1.225909,1.420455,1.612273,1.864545,2.726364,3.186818,3.814091,4.450909,15366.607000,14608.208000,2.754091,2.752273,False,True
2008-11-30,4.004444,0.387667,0.093333,0.193889,0.741111,1.066667,1.212778,1.514444,2.291667,2.818889,3.526667,4.271111,15282.140934,14528.782507,3.690556,2.888333,False,True
2008-12-31,2.870000,0.155161,0.030000,0.034091,0.255909,0.494545,0.820909,1.070000,1.521818,1.892727,2.416364,3.175909,15223.411204,14470.870130,1.761818,2.170000,False,True
2009-01-31,3.128000,0.154194,0.050500,0.129500,0.304500,0.444500,0.807000,1.134000,1.596500,1.978000,2.517500,3.457000,15187.475000,14430.901000,1.585000,1.912000,False,True
2009-02-28,3.586842,0.222143,0.219474,0.295263,0.458947,0.622632,0.975263,1.368947,1.871579,2.303158,2.870000,3.834737,15169.609220,14405.461765,1.289474,1.752105,False,True
2009-03-31,3.643182,0.180645,0.104545,0.215909,0.425909,0.644091,0.931364,1.312273,1.815909,2.417727,2.819545,3.780000,15161.642224,14387.858668,1.227273,1.709091,False,True
2009-04-30,3.760000,0.150333,0.095238,0.158095,0.350476,0.547619,0.927143,1.316667,1.858095,2.465238,2.927143,3.843810,15161.772000,14381.236000,1.110476,1.567619,False,True
2009-05-31,4.227000,0.177419,0.137500,0.177000,0.303500,0.501500,0.929500,1.392500,2.134000,2.810500,3.293000,4.219500,15167.606190,14385.970936,1.071000,1.717000,False,True
2009-06-30,4.516364,0.206333,0.098636,0.178636,0.314545,0.513636,1.184091,1.759545,2.705909,3.365000,3.721818,4.508636,15183.363644,14406.209202,1.180000,1.862273,False,True
2020-01-31,2.216190,1.550645,1.533333,1.552381,1.563333,1.532857,1.519048,1.518095,1.562381,1.669524,1.757619,2.067143,18989.877000,21538.032000,-0.090000,0.036667,True,True
2020-02-29,1.970526,1.583103,1.576316,1.544737,1.509474,1.405789,1.331053,1.306842,1.323684,1.423158,1.504211,1.806842,18401.177704,20845.207029,-0.257368,-0.111579,True,True
2020-03-31,1.455000,0.652258,0.370455,0.295455,0.297273,0.331818,0.448182,0.503636,0.591818,0.780455,0.870000,1.257273,17718.525303,20033.690296,-0.082727,-0.116818,True,True
2020-04-30,1.265238,0.049000,0.110000,0.138095,0.169048,0.184286,0.224762,0.279524,0.388095,0.545238,0.657619,1.064286,17378.712000,19636.731000,-0.370476,-0.445714,False,True
2020-05-31,1.378000,0.050000,0.098500,0.127500,0.153500,0.161500,0.170500,0.218000,0.339500,0.525000,0.674000,1.124500,17621.306810,19950.509573,-0.425500,-0.441500,False,True
2020-06-30,1.493636,0.077667,0.130000,0.159545,0.180000,0.176364,0.185000,0.224545,0.344545,0.554545,0.728636,1.266364,18189.393473,20662.577688,-0.669545,-0.544545,False,True
2020-07-31,1.310455,0.092581,0.105909,0.126818,0.141364,0.145455,0.148182,0.173636,0.278636,0.462273,0.623636,1.091818,18743.720000,21362.428000,-1.034545,-0.832727,False,True
2022-03-31,2.406522,0.200968,0.179565,0.447391,0.855652,1.335217,1.909565,2.085652,2.109130,2.150435,2.127826,2.513478,19879.275640,25065.170337,-1.301739,-0.718696,False,True
2022-04-30,2.812000,0.330000,0.307000,0.763500,1.261500,1.887000,2.538000,2.724000,2.777500,2.795000,2.747500,2.986500,19895.271000,25248.476000,-0.538000,-0.136500,False,True
2022-05-31,3.065714,0.765484,0.580952,0.992857,1.494762,2.059524,2.616667,2.790000,2.874286,2.921429,2.898095,3.258571,19938.243657,25422.354451,-0.152857,0.209524,False,True

In [5]:
data["RecessionFollowing18Months"] = False
data["RecessionFollowing18Months"] = data.apply(lambda x: True in data.loc[x.name:][:19]["Recession"].values, axis = 1)
data["RGDP Growth"] = np.log(data["RGDP"]).diff(12).mul(100)
data["NGDP Growth"] = np.log(data["NGDP"]).diff(12).mul(100)
data.to_csv("C:/Users/JLCat/Documents/For NDSU/EnrichmentCourses/DataScienceCertificate/STAT714/Homework/Data/ProjectYieldCurveData.csv")
data.diff(12).to_csv("C:/Users/JLCat/Documents/For NDSU/EnrichmentCourses/DataScienceCertificate/STAT714/Homework/Data/ProjectYieldCurveData12MonthDiff.csv")